# Car Mileage Analysis

Business Objective: Increase in Mileage

Contraints : Decrease in Features 

## Loading Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.metrics import mean_squared_error


## Loading Data Set

In [2]:
dd= pd.read_csv(r"C:\Users\hi\Desktop\Innomatics\ML Sample Docs\Cars.csv")

In [5]:
dd

HP        MPG  VOL          SP         WT
0    49  53.700681   89  104.185353  28.762059
1    55  50.013401   92  105.461264  30.466833
2    55  50.013401   92  105.461264  30.193597
3    70  45.696322   92  113.461264  30.632114
4    53  50.504232   92  104.461264  29.889149
..  ...        ...  ...         ...        ...
76  322  36.900000   50  169.598513  16.132947
77  238  19.197888  115  150.576579  37.923113
78  263  34.000000   50  151.598513  15.769625
79  295  19.833733  119  167.944460  39.423099
80  236  12.101263  107  139.840817  34.948615

[81 rows x 5 columns]

In [4]:
dd.columns

Index(['HP', 'MPG', 'VOL', 'SP', 'WT'], dtype='object')

## Splitting data into Train and Test

In [6]:
X = dd[['HP', 'VOL', 'SP', 'WT']]

In [7]:
y= dd[['MPG']]

In [8]:
X.shape

(81, 4)

In [9]:
y.shape

(81, 1)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.80, random_state = 55)

In [11]:
X_train

HP  VOL          SP         WT
11   92   50  117.598513  15.753535
34   81  101  111.288996  32.701644
25   92   50  114.598513  16.043175
58  100   94  112.645204  30.615283
2    55   92  105.461264  30.193597
..  ...  ...         ...        ...
29  103  107  121.840817  35.549360
72  162  132  133.140074  43.353123
39  130   92  128.461264  30.115434
26   92  117  120.760520  38.062823
77  238  115  150.576579  37.923113

[64 rows x 4 columns]

## Model Building

In [12]:
reg = LinearRegression()

In [13]:
reg.fit(X_train,y_train)

LinearRegression()

In [21]:
reg.predict([[80,90,120,30]])

C:\Users\hi\anaconda4\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[43.43566369]])

In [22]:
reg.intercept_

array([29.32412565])

In [23]:
reg.coef_

array([[-0.20605409, -0.39207593,  0.4128234 ,  0.54479636]])

## Model Evaluation

## Linear Regression

In [24]:
reg = LinearRegression()
reg.fit(X_train,y_train)
y_pre = reg.predict(X_test)
mean_squared_error(y_pre, y_test)
np.sqrt(mean_squared_error(y_pre, y_test))

4.049664209763323

## KNN Regression

In [26]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor()
knn.fit(X_train,y_train)
y_pre = knn.predict(X_test)
mean_squared_error(y_pre, y_test)
np.sqrt(mean_squared_error(y_pre, y_test))

3.374051494642686

## Decision Tree

In [27]:
from sklearn.tree import DecisionTreeRegressor
tre = DecisionTreeRegressor()
tre.fit(X_train,y_train)
y_pre = tre.predict(X_test)
mean_squared_error(y_pre, y_test)
np.sqrt(mean_squared_error(y_pre, y_test))

2.9984462215318315

## Random Forest

In [28]:
from sklearn.ensemble import RandomForestRegressor
RF = RandomForestRegressor()
RF.fit(X_train,y_train)
y_pre = RF.predict(X_test)
mean_squared_error(y_pre, y_test)
np.sqrt(mean_squared_error(y_pre, y_test))

C:\Users\hi\anaconda4\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


3.0448922382662404